
FROM ruby:3.3.5-slim

WORKDIR /rails

RUN apt-get update -qq && apt-get install -y nodejs yarn build-essential git

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"]
