version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["rails", "server", "-b", "0.0.0.0"]
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    depends_on:
      - mongo
      - redis
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["bundle", "exec", "sidekiq"]
